# ===============
# Header
# ===============
# Navigation menu
menu:
  Home: /
  Call for Papers: /call-for-papers
  Submissions: /submission
  Important Dates: /important-dates
  Program Committee: /program-committee
  Chairs: /workshop-chairs
  Previous Editions: /previous-editions

# RSS link
rss: /atom.xml
# Path of title banner image of page top
banner: "images/banner.jpg"
# Subtitle of page top
subtitle:
# Header links with icon, specified links will appear at the top right corner of the page
links:

# ===============
# Content
# ===============
excerpt_link: Read More
fancybox: true

# ===============
# Footer
# ===============
copyright:

# ===============
# Sidebar
# ===============
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# ===============
# Widget behavior
# ===============
archive_type: 'monthly'
show_count: false
recent_posts_limits: 5

# ===============
# Miscellaneous
# ===============
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

# ===============
# Comment system
# ===============
disqus_shortname:
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  pageSize: 10
  avatar: mm
  lang: zh-cn
  placeholder: Just go go
  guest_info: nick,mail,link
